name: ESLint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Check
        run: pnpm run start:lint

      - name: Start build
        run: pnpm run start:build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CREATOR_URL: ${{ secrets.NEXT_PUBLIC_CREATOR_URL }}
          NEXT_PUBLIC_FAN_URL: ${{ secrets.NEXT_PUBLIC_FAN_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_ADMIN_URL }}
          NEXT_PUBLIC_APP_DOMAINS: ${{ secrets.NEXT_PUBLIC_APP_DOMAINS }}
